### ISSUE TITLE
For some reason extending with stylelint removes other rules like no-dupe-keys

### ISSUE THREAD

**Issue by wbolduc** [stylelint/stylelint-config-recommended#112]
> Clearly describe the bug

Extending with stylelint seems to disabled other rules like no-dupe-keys

> What steps are needed to reproduce the bug?

`{
	"env": {
		"browser": true,
		"es2021": true,
		"jest/globals": true
	},
	"extends": [
		//"stylelint-config-recommended",
		"eslint:recommended",
		"plugin:react/recommended",
		"prettier",
		"plugin:react-hooks/recommended"
	],
	"parserOptions": {
		"ecmaFeatures": {
			"jsx": true
		},
		"ecmaVersion": 12,
		"sourceType": "module"
	},
	"plugins": ["react", "prettier", "jest"],
	"rules": {
		"react/prop-types": 1,
		"no-var": 2,
		"prefer-const": 2,
		"no-console": ["warn", { "allow": ["warn", "error", "info"] }],
		"func-names": 0,
		"no-useless-rename": 2,
		"no-duplicate-imports": 1,
		"react/display-name": 0
	}
}
`

This is my .eslintrc.json, uncommenting the stylelint line turns off other rules like no-dupe-keys

> What did you expect to happen?

no-dupe-keys linting should still happen

> What actually happened (e.g. what warnings or errors did you get)?

no-dupe-keys is no longer being shown as an error

**Comment by hudochenkov** [comment]
Stylelint is completely different tool that ESLint. You can't use the same config file for both.

https://stylelint.io/user-guide/get-started
