### ISSUE TITLE
Why somes possible errors are not turned on ?

### ISSUE THREAD

**Issue by drazik** [stylelint/stylelint-config-recommended#13]
Hello,

Some rules listed in the [possible errors list](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#possible-errors) are not turned on by this config : 

* `font-family-no-missing-generic-family-keyword`
* `no-descending-specificity`
* `no-duplicate-at-import-rules`
* `no-duplicate-selectors`
* `no-unknown-animations`

Since this recommended config is turning on all possible errors rules, I am wondering if there is a reason for the fact that these rules are not turned on in this config.

Would be happy to make a PR if it is just an oversight.

Thanks !

**Comment by drazik** [comment]
Hum, closing because I just saw https://github.com/stylelint/stylelint-config-recommended/pull/9 which attends to fix this. Sorry, I must have investigated before posting this issue.

**Comment by jeddy3** [comment]
@drazik Thanks for the issue, I'm going to reopen this and only close it once the relevant PRs are merged.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint-config-recommended/pull/16
