### ISSUE TITLE
`Cannot parse selector` with double dash comments @ Emotion JS

### ISSUE THREAD

**Issue by joaosaro** [stylelint/stylelint-config-recommended#133]
### What steps are needed to reproduce the bug?

Use a SPA (React) with [Emotion JS](https://emotion.sh/docs/introduction) where double slash comments are allowed.

Rule added: `'no-invalid-double-slash-comments': null`.

Example:

```
const classNameStyles = css`
	display: flex;
	align-items: center;

	// Comment throws a parse error
	.class-target {
		max-width: 100px;
	}
`;
```

There is a way to avoid this? If yes, which extended configuration should we use?

### What did you expect to happen?

It passes since this is allowed with our configuration (@emotion/babel-plugin). Or there was a way to exclude with a rule.

### What actually happened?

It shows a parseError:

`✖  Cannot parse selector   parseError`

**Comment by jeddy3** [comment]
Which [custom syntax](https://stylelint.io/user-guide/usage/options#customsyntax) are you using?

**Comment by jeddy3** [comment]
Closing. You're welcome to open a new issue in the main stylelint repo using the full template.
