### ISSUE TITLE
Disable declaration-block-no-redundant-longhand-properties

### ISSUE THREAD

**Issue by sapegin** [stylelint/stylelint-config-recommended#14]
The [declaration-block-no-redundant-longhand-properties](https://stylelint.io/user-guide/rules/declaration-block-no-redundant-longhand-properties/) may lead to less readable code. Some shorthands are hard to remember, for example [flex](http://developer.mozilla.org/en-US/docs/Web/CSS/flex). Even `padding` and `margin` requires me to think a bit every time I use them, especially if some values are missed (`padding: 1px 2px 3px`).

I guess the reason to have this rule is to make code shorter but we have CSS minifiers and I’d recommend to use one instead of doing their work manually. So let developers be clear and explicit when they feel it’s needed.

A few links and discussions:

* https://twitter.com/oleg008/status/931125923486846976
* https://twitter.com/iamsapegin/status/931173309164785664
* https://csswizardry.com/2016/12/css-shorthand-syntax-considered-an-anti-pattern/

**Comment by jeddy3** [comment]
Fair points.

Additionally, the `*-redundant-*` rules ([`declaration-block-no-redundant-longhand-properties`](https://stylelint.io/user-guide/rules/declaration-block-no-redundant-longhand-properties/) & [`shorthand-property-no-redundant-values`](https://stylelint.io/user-guide/rules/shorthand-property-no-redundant-values/)) do feel more like preferences than "possible errors", unlike rules such as [`declaration-block-no-shorthand-property-overrides`](https://stylelint.io/user-guide/rules/declaration-block-no-shorthand-property-overrides/). I don't see any harm in bumping these two `*-redundant-*` rules into the [limit language features](https://stylelint.io/user-guide/rules/#limit-language-features) list and out of this recommended config.

@stylelint/core Does anyone else have any thoughts on this?

**Comment by hudochenkov** [comment]
I agree with both of you that this rule is more a personal preference rather error or best practice.

@jeddy3 agree with you to move these rules to Limit language features and remove them from recommended config. Shall we move them to standard config then?

**Comment by sapegin** [comment]
I’ve made two PRs, please have a look. 

What about the standard config? For me these rules are still too opinionated to be in the standard config.

**Comment by jeddy3** [comment]
> Shall we move them to standard config then?

I think we keep them out for now as they are apparently divisive. Nor could I find any reference to this being a common convention in the guides we reference in the standard config README.

> I’ve made two PRs, please have a look.

Thanks!
