### ISSUE TITLE
Stylelint peer dependencies in not up to date

### ISSUE THREAD

**Issue by furdzik** [stylelint/stylelint-config-recommended#164]
Maybe you could consider changing it for something like this?

```
      "peerDependencies": {
        "stylelint": "^14",
      }
```

**Comment by ybiquitous** [comment]
@furdzik Could you please show us what kind of inconveniences you have? 

When installing the latest version of `stylelint-config-recommended`, the latest version of `stylelint` is also installed:

```console
$ ls -a
.  ..

$ npm i stylelint-config-recommended
...

$ npm ls stylelint
foo@ /private/tmp/foo
└─┬ stylelint-config-recommended@7.0.0
  └── stylelint@14.8.5
```

The current `peerDependencies` is as follow:

https://github.com/stylelint/stylelint-config-recommended/blob/565f52431d6aee679a4eb42dce1c388c85ee0bb3/package.json#L61-L63

**Comment by furdzik** [comment]
@ybiquitous
When I install this package, I had an error about not compatible peerDependencies. But I can't reproduce now, probably some npm issue.
I am sorry, I'm closing this issue.
