### ISSUE TITLE
declaration-block-no-redundant-longhand-properties

### ISSUE THREAD

**Issue by Mottie** [stylelint/stylelint-config-recommended#18]
The [changelog for v2.0.0](https://github.com/stylelint/stylelint-config-recommended/blob/master/CHANGELOG.md#200) states that the `declaration-block-no-redundant-longhand-properties` rule was removed, yet it is still present.

It *was* removed in https://github.com/stylelint/stylelint-config-recommended/commit/e18c2b80bee48b87c63d8585dcd3dded925e49c9, but added back in https://github.com/stylelint/stylelint-config-recommended/commit/6bae0c9683743983262961470cd744b1d86a12cc (see line 15).

**Comment by hudochenkov** [comment]
Thank you for the report, @Mottie! Fixing in https://github.com/stylelint/stylelint-config-recommended/pull/19

**Comment by ntwb** [comment]
I've just published `stylelint-config-recommended` version 2.0.1

• https://github.com/stylelint/stylelint-config-recommended/releases/tag/2.0.1
• https://www.npmjs.com/package/stylelint-config-recommended

Thanks @Mottie & @hudochenkov
