### ISSUE TITLE
There are four unknown rules

### ISSUE THREAD

**Issue by vortesnail** [stylelint/stylelint-config-recommended#192]
### What steps are needed to reproduce the bug?

I installed `stylelint-config-recommended-vue` , which depends on `stylelint-config-recommended` , reporting an error like this:

![image](https://github.com/stylelint/stylelint-config-recommended/assets/18679842/b526d0e9-e056-45c6-8543-057627726714)

I checked out `stylelint-config-recommended`
There are indeed these four rules, and I will not report an error if I remove them

unknown rule list:

```
annotation-no-unknown
function-no-unknown
keyframe-block-no-duplicate-selectors
selector-anb-no-unmatchable
```

Note: stylelint@14.3.0

### What did you expect to happen?

no error

### What actually happened?

a error happened

**Comment by ybiquitous** [comment]
@vortesnail Thanks for using the template. I guess your dependency tree doesn't satisfy the following requirement:

https://github.com/stylelint/stylelint-config-recommended/blob/b35e61355d4a9853532a9f977219453456d6b1bc/package.json#L64-L66

Could you please update the Stylelint dependencies and try it again?

**Comment by vortesnail** [comment]
> 

Thanks, solved my problem
