### ISSUE TITLE
What the difference ?

### ISSUE THREAD

**Issue by DimaRGB** [stylelint/stylelint-config-recommended#2]
What the difference between [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard) ?

**Comment by ntwb** [comment]
`stylelint-config-recommended`: Turns on all the **possible errors** rules within stylelint.

`stylelint-config-standard`: Extends `stylelint-config-recommended` and turns on additional rules to enforce the common **stylistic** conventions

**Comment by jeddy3** [comment]
@DimaRGB We're in the process of updating the docs regarding this. Hopefully, that'll make things clearer.

See: https://github.com/stylelint/stylelint-config-standard/pull/83 & https://github.com/stylelint/stylelint/pull/2727

**Comment by DimaRGB** [comment]
Thanks 👍

**Comment by SevenOutman** [comment]
Is there any advice on whether I should base my own config on the standard or recommended config?

**Comment by jeddy3** [comment]
@SevenOutman It depends on what you want to do, but most of the time [we suggest](https://stylelint.io/user-guide/get-started) starting with a standard config (even if [you're using a pretty printer](https://stylelint.io/about/linting#pretty-printers)).

I'd only suggest using the recommended config if you have very specific and idiosyncratic needs, which require you to craft your own stylistics and limiting rules.

**Comment by SevenOutman** [comment]
@jeddy3 Thanks for your explanation!
