### ISSUE TITLE
node version

### ISSUE THREAD

**Issue by zhouzhi-zz** [stylelint/stylelint-config-recommended#210]
### What steps are needed to reproduce the bug?

node -v
14.21.0
yarn add stylelint-config-recommended
stylelint-config-recommended@14.0.0: The engine "node" is incompatible with this module. Expected version ">=18.12.0". Got "14.21.0"

### What did you expect to happen?

nothing happend, success install.

### What actually happened?

In the readme docs, node just than 14 is ok, but this error message talk me I need more than 18

**Comment by jeddy3** [comment]
@zhouzhi-zz Thanks for the report.

This package requires Node.js 18+:

https://github.com/stylelint/stylelint-config-recommended/blob/95ecede5faa73a23241b877e152a37218c65277c/package.json#L64-L66

> In the readme docs, node just than 14 is ok

If you're referring to this number

<img width="471" alt="Screenshot 2024-01-18 at 09 20 43" src="https://github.com/stylelint/stylelint-config-recommended/assets/808227/c52d6f84-8549-403d-b119-d427da46c988">

then that's the npm package number and not related to the Node.js version
