### ISSUE TITLE
Remove stylelint from dependabot

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint-config-recommended#213]
Do we want to remove stylelint from dependabot updates because we want to separate peer dep from dev dep?

Ref: https://github.com/stylelint/stylelint-config-recommended/pull/212

**Comment by ybiquitous** [comment]
Agree 👍🏼 We can use the [`ignore`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore) option in `dependabot.yml`.
