### ISSUE TITLE
Add function-calc-no-invalid

### ISSUE THREAD

**Issue by lydell** [stylelint/stylelint-config-recommended#41]
https://github.com/stylelint/stylelint/blob/master/lib/rules/function-calc-no-invalid/README.md

It’s a new “Possible errors” errors added in stylelint 9.10.0

**Comment by jeddy3** [comment]
Sounds good to me.

I think we'll want to address the emerging issues with the rule (https://github.com/stylelint/stylelint/issues/3908, https://github.com/stylelint/stylelint/issues/3912) before we release, though.
