### ISSUE TITLE
Add declaration-block-no-duplicate-custom-properties

### ISSUE THREAD

**Issue by thernstig** [stylelint/stylelint-config-recommended#80]
> What is the problem you're trying to solve?

`declaration-block-no-duplicate-custom-properties` was added to stylelint 13.10.0, but it does not exist in stylelint-config-standard yet.

> What solution would you like to see?

I believe it would be a nice addition to this config.

**Comment by jeddy3** [comment]
@thernstig Thanks for the request and for using the template.

Sounds good to me. 

(I transferred this issue over to the `recommended` config as that's where we turn on the possible error rules).
