### ISSUE TITLE
stylelint: no rules found `declaration-block-no-duplicate-custom-properties`

### ISSUE THREAD

**Issue by indiejoseph** [stylelint/stylelint-config-recommended#91]
After upgraded to 4.0.0, i got an error from stylelint, and i have upgraded the stylelint to latest version 13.12.0.

**Comment by jeddy3** [comment]
This usually happens if you've got a globally installed version of the stylelint that you haven't updated.

Run:

```
npm uninstall -g stylelint
npm install -D stylelint@latest stylelint-config-recommended
```

Feel free to reopen if that isn't the case.
