### ISSUE TITLE
Allow Custom Element Type Selectors

### ISSUE THREAD

**Issue by tysongach** [stylelint/stylelint-config-recommended#94]
> Clearly describe the bug

When using stylelint-config-recommended, stylelint throws an error against the [`selector-type-no-unknown` rule](https://stylelint.io/user-guide/rules/selector-type-no-unknown) when using a [Type Selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Type_selectors) to style a HTML Custom Element.

> What steps are needed to reproduce the bug?

Run stylelint-config-recommended against some CSS which includes a Type Selector of an HTML Custom Element, for example:

```css
custom-element { color: red; }
```

> What did you expect to happen?

That stylelint would not error against the `selector-type-no-unknown` rule when using a Type Selector to style a HTML Custom Element, because they are valid HTML according the [WHATWG HTML Living Standard](https://html.spec.whatwg.org/multipage/custom-elements.html).

[`selector-type-no-unknown` has an option for ignoring Custom Elements](https://stylelint.io/user-guide/rules/selector-type-no-unknown#ignore-custom-elements-default-namespace), which I feel should be enabled in this config, so that it doesn’t consider a valid selector a possible error.

> What actually happened (e.g. what warnings or errors did you get)?

stylelint outputs the following error:

```
Unexpected unknown type selector "custom-element"   selector-type-no-unknown
```

**Comment by jeddy3** [comment]
Hi @tysongach 👋 

Thanks for using the template and for the detailed write-up.

With the increasing usage of custom elements, I think it makes sense to use the `ignore["custom-elements"]` in this config.

We can roll it into the next release as we've got two new rules coming in stylelint that should be added to this config.

**Comment by tysongach** [comment]
Lovely - I’ve opened a PR here: https://github.com/stylelint/stylelint-config-recommended/pull/95

Thanks, @jeddy3!
